// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmJSZ_DbveNqHS3ISNi3pJBfISIk7_ew',
    appId: '1:823810221730:web:e22bf76d90685e8807d9fb',
    messagingSenderId: '823810221730',
    projectId: 'medlytic-d891f',
    authDomain: 'medlytic-d891f.firebaseapp.com',
    storageBucket: 'medlytic-d891f.firebasestorage.app',
    measurementId: 'G-7CVH27J15F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDfJRaFGVcSdyI3IBQe3ewTPsbVlV2ptE',
    appId: '1:823810221730:android:9e99fb60a7437e6b07d9fb',
    messagingSenderId: '823810221730',
    projectId: 'medlytic-d891f',
    storageBucket: 'medlytic-d891f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnkha_L-VIbkre6Bzn0Tkn8AU3NrvxE_8',
    appId: '1:823810221730:ios:fb7a1bb3a6ec32a607d9fb',
    messagingSenderId: '823810221730',
    projectId: 'medlytic-d891f',
    storageBucket: 'medlytic-d891f.firebasestorage.app',
    iosBundleId: 'com.example.medlytic',
  );
}
